# Generated by Django 2.0.7 on 2018-08-03 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passport', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Park_Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=128)),
                ('park_name', models.CharField(max_length=128)),
                ('review', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='your_park',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='your_park',
            name='review',
        ),
    ]
