# Generated by Django 2.0.7 on 2018-08-03 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passport', '0002_auto_20180803_0050'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=128)),
                ('friend', models.CharField(max_length=128)),
            ],
        ),
    ]
